@echo off
echo 🚀 Starting NFT Collection App...
cd /d "C:\Users\Демид\Documents\GitHub\Nft-collection-"
echo 📁 Current directory: %CD%
echo 🔍 Checking Node.js...
node --version
echo 🔍 Checking npm...
npm --version
echo 🚀 Starting simple NFT app...
node simple-app.js
pause
