name: Generate NFT Metadata

on:
  push:
    paths:
      - 'images/**.png'
      - 'images/**.jpg'
      - 'images/**.jpeg'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r scripts/requirements.txt

      - name: Generate Metadata
        run: |
          python scripts/generate_caption.py