name: Generate Image Descriptions

on:
  push:
    paths:
      - 'images/**/*.{jpg,jpeg,png,gif}'

jobs:
  describe-images:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp PyGithub python-dotenv

      - name: Generate descriptions
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python .github/scripts/generate_descriptions.py

      - name: Commit and push descriptions
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add images/*.txt
          git diff --quiet --exit-code || git commit -m "🖼️ Auto-generate image descriptions"
          git push
