name: Upload NFT Description

on:
  push:
    paths:
      - 'description/**.json'
    branches:
      - main

jobs:
  upload-description:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Commit & Push new descriptions
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add description/*.json
          git commit -m "📝 Add/update NFT description JSON"
          git push