name: Start Telegram Bot

on:
  workflow_dispatch:   # запуск вручную
  push:
    branches:
      - main

jobs:
  run-telegram-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Write .env from GitHub Secrets
      run: |
        echo "TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}" >> .env
        echo "MY_TOKEN=${{ secrets.MY_TOKEN }}" >> .env
        echo "MY_REPO=${{ secrets.MY_REPO }}" >> .env
        echo "GITHUB_BRANCH=main" >> .env
        echo "GITHUB_PATH_IMG=images" >> .env
        echo "GITHUB_PATH_DESC=description" >> .env

    - name: Run bot
      run: python bot_main_git_upload_and_watch.py
